services:
  guacd:
    build:
      context: .
      dockerfile: guacd/Dockerfile
    image: guacamole/guacd:1.6.0-cjk
    restart: always
    volumes:
      - ./drive:/drive:rw
      - ./record:/record:rw
  postgres:
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: "ChooseYourOwnPasswordHere1234"
      POSTGRES_USER: guacamole_user
    image: postgres:15.2-alpine
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d:z
      - ./data:/var/lib/postgresql/data:Z
  guacamole:
    group_add:
      - "1000"
    depends_on:
      - guacd
      - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_HOSTNAME: postgres
      POSTGRESQL_PASSWORD: "ChooseYourOwnPasswordHere1234"
      POSTGRESQL_USERNAME: guacamole_user
      RECORDING_SEARCH_PATH: /record
    image: guacamole/guacamole:1.6.0
    volumes:
      - ./record:/record:rw
    ports:
      - 8080:8080
    restart: always
